In [3]:
import pandas as pd
data = pd.read_csv('covid.csv')
data

id  sex  patient_type  entry_date date_symptoms   date_died  \
0       16169f    2             1  04-05-2020    02-05-2020  9999-99-99   
1       1009bf    2             1  19-03-2020    17-03-2020  9999-99-99   
2       167386    1             2  06-04-2020    01-04-2020  9999-99-99   
3       0b5948    2             2  17-04-2020    10-04-2020  9999-99-99   
4       0d01b5    1             2  13-04-2020    13-04-2020  22-04-2020   
...        ...  ...           ...         ...           ...         ...   
566597  01ff60    2             1  13-05-2020    03-05-2020  9999-99-99   
566598  047cd1    1             1  07-04-2020    06-04-2020  9999-99-99   
566599  1beb81    1             2  14-05-2020    01-05-2020  9999-99-99   
566600  16fb02    1             1  31-05-2020    29-05-2020  9999-99-99   
566601  0021c9    2             1  16-05-2020    16-05-2020  9999-99-99   

        intubed  pneumonia  age  pregnancy  ...  inmsupr  hypertension  \
0            97          2   27         97  ...        2             2   
1            97          2   24         97  ...        2             2   
2             2          2   54          2  ...        2             2   
3             2          1   30         97  ...        2             2   
4             2          2   60          2  ...        2             1   
...         ...        ...  ...        ...  ...      ...           ...   
566597       97          2   58         97  ...        2             2   
566598       97          2   48          2  ...        2             2   
566599        2          1   49          2  ...        2             2   
566600       97          1   43          2  ...        2             2   
566601       97          1   65         97  ...        2             1   

        other_disease  cardiovascular  obesity  renal_chronic  tobacco  \
0                   2               2        2              2        2   
1                   2               2        2              2        2   
2                   2               2        1              2        2   
3                   2               2        2              2        2   
4                   2               1        2              2        2   
...               ...             ...      ...            ...      ...   
566597              2               2        2              2        2   
566598              2               2        2              2        2   
566599              2               2        1              2        2   
566600              2               2        2              2        2   
566601              2               2        1              2        2   

        contact_other_covid  covid_res  icu  
0                         2          1   97  
1                        99          1   97  
2                        99          1    2  
3                        99          1    2  
4                        99          1    2  
...                     ...        ...  ...  
566597                    2          3   97  
566598                    2          3   97  
566599                   99          3    2  
566600                    2          3   97  
566601                    2          3   97  

[566602 rows x 23 columns]

In [4]:
data['intubed'].value_counts()

97    444689
2     111824
1       9965
99       124
Name: intubed, dtype: int64

In [5]:
data.drop(data[data['intubed'] == 97].index, inplace = True)

In [6]:
data.drop(data[data['intubed'] == 99].index, inplace = True)

In [7]:
data['intubed'].value_counts()

2    111824
1      9965
Name: intubed, dtype: int64

In [8]:
data

id  sex  patient_type  entry_date date_symptoms   date_died  \
2         167386    1             2  06-04-2020    01-04-2020  9999-99-99   
3         0b5948    2             2  17-04-2020    10-04-2020  9999-99-99   
4         0d01b5    1             2  13-04-2020    13-04-2020  22-04-2020   
5         1beec8    2             2  16-04-2020    16-04-2020  29-04-2020   
6       1.75E+56    2             2  22-04-2020    13-04-2020  9999-99-99   
...          ...  ...           ...         ...           ...         ...   
566584    093a47    2             2  02-05-2020    02-05-2020  9999-99-99   
566590    067bbd    2             2  07-06-2020    24-05-2020  9999-99-99   
566591  5.60E+40    2             2  08-05-2020    08-05-2020  13-05-2020   
566593    150615    1             2  12-05-2020    09-05-2020  9999-99-99   
566599    1beb81    1             2  14-05-2020    01-05-2020  9999-99-99   

        intubed  pneumonia  age  pregnancy  ...  inmsupr  hypertension  \
2             2          2   54          2  ...        2             2   
3             2          1   30         97  ...        2             2   
4             2          2   60          2  ...        2             1   
5             2          1   47         97  ...        2             2   
6             2          2   63         97  ...        2             1   
...         ...        ...  ...        ...  ...      ...           ...   
566584        2          1   45         97  ...        2             2   
566590        1          1   68         97  ...        2             1   
566591        1          1   48         97  ...        2             1   
566593        2          1   31         98  ...        2             2   
566599        2          1   49          2  ...        2             2   

        other_disease  cardiovascular  obesity  renal_chronic  tobacco  \
2                   2               2        1              2        2   
3                   2               2        2              2        2   
4                   2               1        2              2        2   
5                   2               2        2              2        2   
6                   2               2        2              2        2   
...               ...             ...      ...            ...      ...   
566584              2               2        2              2        2   
566590              2               2        1              2        2   
566591              2               2        2              2        2   
566593              2               2        2              2        2   
566599              2               2        1              2        2   

        contact_other_covid  covid_res  icu  
2                        99          1    2  
3                        99          1    2  
4                        99          1    2  
5                        99          1    1  
6                        99          1    2  
...                     ...        ...  ...  
566584                   99          3    2  
566590                    2          3    1  
566591                    2          3    1  
566593                   99          3    2  
566599                   99          3    2  

[121789 rows x 23 columns]

In [9]:
data['age'].value_counts()

56     2905
52     2780
60     2734
61     2689
59     2671
       ... 
106       1
109       1
115       1
103       1
118       1
Name: age, Length: 110, dtype: int64

In [10]:
print(max(data['age']),min(data['age']))

118 0


In [11]:
data[data['age'] == 0]

id  sex  patient_type  entry_date date_symptoms   date_died  \
356     102ad8    2             2  26-04-2020    26-04-2020  9999-99-99   
714     16b635    2             2  06-05-2020    06-05-2020  9999-99-99   
1722    1b52c3    1             2  19-05-2020    19-05-2020  9999-99-99   
2358    1b82ee    1             2  13-05-2020    13-05-2020  22-05-2020   
3428    1e0c53    1             2  29-05-2020    29-05-2020  9999-99-99   
...        ...  ...           ...         ...           ...         ...   
563020  17b90b    2             2  01-06-2020    01-06-2020  9999-99-99   
563791  070fe0    2             2  01-06-2020    01-06-2020  9999-99-99   
564230  1c1e58    1             2  24-06-2020    24-06-2020  9999-99-99   
564543  0b45fe    1             2  28-05-2020    28-05-2020  9999-99-99   
565651  0cd5df    1             2  24-06-2020    24-06-2020  9999-99-99   

        intubed  pneumonia  age  pregnancy  ...  inmsupr  hypertension  \
356           2          2    0         97  ...        2             2   
714           2          2    0         97  ...        2             2   
1722          2          2    0          2  ...        2             2   
2358          2          2    0          2  ...        2             2   
3428          2          2    0          2  ...        2             2   
...         ...        ...  ...        ...  ...      ...           ...   
563020        2          2    0         97  ...        2             2   
563791        1          1    0         97  ...        2             2   
564230        2          2    0          2  ...        2             2   
564543        2          2    0          2  ...        2             2   
565651        2          2    0          2  ...        2             2   

        other_disease  cardiovascular  obesity  renal_chronic  tobacco  \
356                 1               2        2              2        2   
714                 2               2        2              2        2   
1722                2               2        2              2        2   
2358                1               2        2              2        2   
3428                2               2        2              2        2   
...               ...             ...      ...            ...      ...   
563020              1               2        2              2        2   
563791              2               1        2              2        2   
564230              2               2        2              2        2   
564543              2               2        2              2        2   
565651              2               2        2              2        2   

        contact_other_covid  covid_res  icu  
356                      99          1    2  
714                      99          1    2  
1722                     99          1    1  
2358                     99          1    1  
3428                     99          1    2  
...                     ...        ...  ...  
563020                   99          3    2  
563791                    2          3    1  
564230                   99          3    2  
564543                    2          3    2  
565651                    1          3    2  

[1586 rows x 23 columns]

In [12]:
def f(x):
    if(x['age']>=0 and x['age']<=17):
        age_br='0-17'
    elif(x['age']>=18 and x['age']<=44):
        age_br='17-44'
    elif(x['age']>=45 and x['age']<=64):
        age_br='45-64'
    elif(x['age']>=65 and x['age']<=74):
        age_br='65-74'
    else:
        age_br='75+'
    return age_br

data['age_bracket'] = data.apply(f,axis=1) 

In [13]:
data

id  sex  patient_type  entry_date date_symptoms   date_died  \
2         167386    1             2  06-04-2020    01-04-2020  9999-99-99   
3         0b5948    2             2  17-04-2020    10-04-2020  9999-99-99   
4         0d01b5    1             2  13-04-2020    13-04-2020  22-04-2020   
5         1beec8    2             2  16-04-2020    16-04-2020  29-04-2020   
6       1.75E+56    2             2  22-04-2020    13-04-2020  9999-99-99   
...          ...  ...           ...         ...           ...         ...   
566584    093a47    2             2  02-05-2020    02-05-2020  9999-99-99   
566590    067bbd    2             2  07-06-2020    24-05-2020  9999-99-99   
566591  5.60E+40    2             2  08-05-2020    08-05-2020  13-05-2020   
566593    150615    1             2  12-05-2020    09-05-2020  9999-99-99   
566599    1beb81    1             2  14-05-2020    01-05-2020  9999-99-99   

        intubed  pneumonia  age  pregnancy  ...  hypertension  other_disease  \
2             2          2   54          2  ...             2              2   
3             2          1   30         97  ...             2              2   
4             2          2   60          2  ...             1              2   
5             2          1   47         97  ...             2              2   
6             2          2   63         97  ...             1              2   
...         ...        ...  ...        ...  ...           ...            ...   
566584        2          1   45         97  ...             2              2   
566590        1          1   68         97  ...             1              2   
566591        1          1   48         97  ...             1              2   
566593        2          1   31         98  ...             2              2   
566599        2          1   49          2  ...             2              2   

        cardiovascular  obesity  renal_chronic  tobacco  contact_other_covid  \
2                    2        1              2        2                   99   
3                    2        2              2        2                   99   
4                    1        2              2        2                   99   
5                    2        2              2        2                   99   
6                    2        2              2        2                   99   
...                ...      ...            ...      ...                  ...   
566584               2        2              2        2                   99   
566590               2        1              2        2                    2   
566591               2        2              2        2                    2   
566593               2        2              2        2                   99   
566599               2        1              2        2                   99   

        covid_res  icu  age_bracket  
2               1    2        45-64  
3               1    2        17-44  
4               1    2        45-64  
5               1    1        45-64  
6               1    2        45-64  
...           ...  ...          ...  
566584          3    2        45-64  
566590          3    1        65-74  
566591          3    1        45-64  
566593          3    2        17-44  
566599          3    2        45-64  

[121789 rows x 24 columns]

In [14]:
for column in data[['intubed','pneumonia','icu','diabetes','hypertension','obesity','cardiovascular','copd','asthma','inmsupr','tobacco','other_disease','renal_chronic']]:
    data.loc[data[column] == 2, column] = 0

In [15]:
data

id  sex  patient_type  entry_date date_symptoms   date_died  \
2         167386    1             2  06-04-2020    01-04-2020  9999-99-99   
3         0b5948    2             2  17-04-2020    10-04-2020  9999-99-99   
4         0d01b5    1             2  13-04-2020    13-04-2020  22-04-2020   
5         1beec8    2             2  16-04-2020    16-04-2020  29-04-2020   
6       1.75E+56    2             2  22-04-2020    13-04-2020  9999-99-99   
...          ...  ...           ...         ...           ...         ...   
566584    093a47    2             2  02-05-2020    02-05-2020  9999-99-99   
566590    067bbd    2             2  07-06-2020    24-05-2020  9999-99-99   
566591  5.60E+40    2             2  08-05-2020    08-05-2020  13-05-2020   
566593    150615    1             2  12-05-2020    09-05-2020  9999-99-99   
566599    1beb81    1             2  14-05-2020    01-05-2020  9999-99-99   

        intubed  pneumonia  age  pregnancy  ...  hypertension  other_disease  \
2             0          0   54          2  ...             0              0   
3             0          1   30         97  ...             0              0   
4             0          0   60          2  ...             1              0   
5             0          1   47         97  ...             0              0   
6             0          0   63         97  ...             1              0   
...         ...        ...  ...        ...  ...           ...            ...   
566584        0          1   45         97  ...             0              0   
566590        1          1   68         97  ...             1              0   
566591        1          1   48         97  ...             1              0   
566593        0          1   31         98  ...             0              0   
566599        0          1   49          2  ...             0              0   

        cardiovascular  obesity  renal_chronic  tobacco  contact_other_covid  \
2                    0        1              0        0                   99   
3                    0        0              0        0                   99   
4                    1        0              0        0                   99   
5                    0        0              0        0                   99   
6                    0        0              0        0                   99   
...                ...      ...            ...      ...                  ...   
566584               0        0              0        0                   99   
566590               0        1              0        0                    2   
566591               0        0              0        0                    2   
566593               0        0              0        0                   99   
566599               0        1              0        0                   99   

        covid_res  icu  age_bracket  
2               1    0        45-64  
3               1    0        17-44  
4               1    0        45-64  
5               1    1        45-64  
6               1    0        45-64  
...           ...  ...          ...  
566584          3    0        45-64  
566590          3    1        65-74  
566591          3    1        45-64  
566593          3    0        17-44  
566599          3    0        45-64  

[121789 rows x 24 columns]

In [16]:
def f1(x):
    if(x['date_died']=='9999-99-99'):
        died = 0
    else:
        died = 1
    return died
data['death'] = data.apply(f1,axis=1)


In [17]:
data['entry_date'] = pd.to_datetime(data['entry_date'])
data['date_symptoms'] = pd.to_datetime(data['date_symptoms'])

In [18]:
data['before_hospital_care'] = data['entry_date']-data['date_symptoms']

In [19]:
data

id  sex  patient_type entry_date date_symptoms   date_died  \
2         167386    1             2 2020-06-04    2020-01-04  9999-99-99   
3         0b5948    2             2 2020-04-17    2020-10-04  9999-99-99   
4         0d01b5    1             2 2020-04-13    2020-04-13  22-04-2020   
5         1beec8    2             2 2020-04-16    2020-04-16  29-04-2020   
6       1.75E+56    2             2 2020-04-22    2020-04-13  9999-99-99   
...          ...  ...           ...        ...           ...         ...   
566584    093a47    2             2 2020-02-05    2020-02-05  9999-99-99   
566590    067bbd    2             2 2020-07-06    2020-05-24  9999-99-99   
566591  5.60E+40    2             2 2020-08-05    2020-08-05  13-05-2020   
566593    150615    1             2 2020-12-05    2020-09-05  9999-99-99   
566599    1beb81    1             2 2020-05-14    2020-01-05  9999-99-99   

        intubed  pneumonia  age  pregnancy  ...  cardiovascular  obesity  \
2             0          0   54          2  ...               0        1   
3             0          1   30         97  ...               0        0   
4             0          0   60          2  ...               1        0   
5             0          1   47         97  ...               0        0   
6             0          0   63         97  ...               0        0   
...         ...        ...  ...        ...  ...             ...      ...   
566584        0          1   45         97  ...               0        0   
566590        1          1   68         97  ...               0        1   
566591        1          1   48         97  ...               0        0   
566593        0          1   31         98  ...               0        0   
566599        0          1   49          2  ...               0        1   

        renal_chronic  tobacco  contact_other_covid  covid_res  icu  \
2                   0        0                   99          1    0   
3                   0        0                   99          1    0   
4                   0        0                   99          1    0   
5                   0        0                   99          1    1   
6                   0        0                   99          1    0   
...               ...      ...                  ...        ...  ...   
566584              0        0                   99          3    0   
566590              0        0                    2          3    1   
566591              0        0                    2          3    1   
566593              0        0                   99          3    0   
566599              0        0                   99          3    0   

        age_bracket  death  before_hospital_care  
2             45-64      0              152 days  
3             17-44      0             -170 days  
4             45-64      1                0 days  
5             45-64      1                0 days  
6             45-64      0                9 days  
...             ...    ...                   ...  
566584        45-64      0                0 days  
566590        65-74      0               43 days  
566591        45-64      1                0 days  
566593        17-44      0               91 days  
566599        45-64      0              130 days  

[121789 rows x 26 columns]

In [20]:
data['patient_type'].value_counts()

2    121789
Name: patient_type, dtype: int64

In [21]:
data['diabetes'].value_counts()

0     85675
1     35445
98      669
Name: diabetes, dtype: int64

In [22]:
data['hypertension'].value_counts()

0     80878
1     40302
98      609
Name: hypertension, dtype: int64

In [23]:
data['obesity'].value_counts()

0     96061
1     25094
98      634
Name: obesity, dtype: int64

In [24]:
data['cardiovascular'].value_counts()

0     114843
1       6300
98       646
Name: cardiovascular, dtype: int64

In [25]:
data['copd'].value_counts()

0     115714
1       5491
98       584
Name: copd, dtype: int64

In [26]:
data['asthma'].value_counts()

0     118062
1       3142
98       585
Name: asthma, dtype: int64

In [27]:
data['inmsupr'].value_counts()

0     116388
1       4722
98       679
Name: inmsupr, dtype: int64

In [28]:
data['tobacco'].value_counts()

0     110414
1      10736
98       639
Name: tobacco, dtype: int64

In [29]:
data['other_disease'].value_counts()

0     113466
1       7282
98      1041
Name: other_disease, dtype: int64

In [30]:
data['renal_chronic'].value_counts()

0     113946
1       7234
98       609
Name: renal_chronic, dtype: int64

In [31]:
for column in data[['diabetes','hypertension','obesity','cardiovascular','copd','asthma','inmsupr','tobacco','other_disease','renal_chronic']]:
    data.drop(data[data[column] == 98].index, inplace = True)

In [32]:
data

id  sex  patient_type entry_date date_symptoms   date_died  \
2         167386    1             2 2020-06-04    2020-01-04  9999-99-99   
3         0b5948    2             2 2020-04-17    2020-10-04  9999-99-99   
4         0d01b5    1             2 2020-04-13    2020-04-13  22-04-2020   
5         1beec8    2             2 2020-04-16    2020-04-16  29-04-2020   
6       1.75E+56    2             2 2020-04-22    2020-04-13  9999-99-99   
...          ...  ...           ...        ...           ...         ...   
566584    093a47    2             2 2020-02-05    2020-02-05  9999-99-99   
566590    067bbd    2             2 2020-07-06    2020-05-24  9999-99-99   
566591  5.60E+40    2             2 2020-08-05    2020-08-05  13-05-2020   
566593    150615    1             2 2020-12-05    2020-09-05  9999-99-99   
566599    1beb81    1             2 2020-05-14    2020-01-05  9999-99-99   

        intubed  pneumonia  age  pregnancy  ...  cardiovascular  obesity  \
2             0          0   54          2  ...               0        1   
3             0          1   30         97  ...               0        0   
4             0          0   60          2  ...               1        0   
5             0          1   47         97  ...               0        0   
6             0          0   63         97  ...               0        0   
...         ...        ...  ...        ...  ...             ...      ...   
566584        0          1   45         97  ...               0        0   
566590        1          1   68         97  ...               0        1   
566591        1          1   48         97  ...               0        0   
566593        0          1   31         98  ...               0        0   
566599        0          1   49          2  ...               0        1   

        renal_chronic  tobacco  contact_other_covid  covid_res  icu  \
2                   0        0                   99          1    0   
3                   0        0                   99          1    0   
4                   0        0                   99          1    0   
5                   0        0                   99          1    1   
6                   0        0                   99          1    0   
...               ...      ...                  ...        ...  ...   
566584              0        0                   99          3    0   
566590              0        0                    2          3    1   
566591              0        0                    2          3    1   
566593              0        0                   99          3    0   
566599              0        0                   99          3    0   

        age_bracket  death  before_hospital_care  
2             45-64      0              152 days  
3             17-44      0             -170 days  
4             45-64      1                0 days  
5             45-64      1                0 days  
6             45-64      0                9 days  
...             ...    ...                   ...  
566584        45-64      0                0 days  
566590        65-74      0               43 days  
566591        45-64      1                0 days  
566593        17-44      0               91 days  
566599        45-64      0              130 days  

[120182 rows x 26 columns]

In [33]:
data['renal_chronic'].value_counts()

0    113012
1      7170
Name: renal_chronic, dtype: int64

In [34]:
data.to_csv('file1.csv') 

In [35]:
!pip install imblearn  

In [36]:
model_data=data.drop(['pregnancy','contact_other_covid','covid_res','id','patient_type','entry_date','date_symptoms','date_died','icu','death','before_hospital_care','age_bracket'],axis=1)

In [37]:
model_data

sex  intubed  pneumonia  age  diabetes  copd  asthma  inmsupr  \
2         1        0          0   54         0     0       0        0   
3         2        0          1   30         0     0       0        0   
4         1        0          0   60         1     0       0        0   
5         2        0          1   47         1     0       0        0   
6         2        0          0   63         0     0       0        0   
...     ...      ...        ...  ...       ...   ...     ...      ...   
566584    2        0          1   45         0     0       0        0   
566590    2        1          1   68         0     0       0        0   
566591    2        1          1   48         1     0       0        0   
566593    1        0          1   31         0     0       0        0   
566599    1        0          1   49         0     0       0        0   

        hypertension  other_disease  cardiovascular  obesity  renal_chronic  \
2                  0              0               0        1              0   
3                  0              0               0        0              0   
4                  1              0               1        0              0   
5                  0              0               0        0              0   
6                  1              0               0        0              0   
...              ...            ...             ...      ...            ...   
566584             0              0               0        0              0   
566590             1              0               0        1              0   
566591             1              0               0        0              0   
566593             0              0               0        0              0   
566599             0              0               0        1              0   

        tobacco  
2             0  
3             0  
4             0  
5             0  
6             0  
...         ...  
566584        0  
566590        0  
566591        0  
566593        0  
566599        0  

[120182 rows x 14 columns]

In [38]:
model_data['age'] = model_data['age']/(15.0+max(model_data['age']))
model_data

sex  intubed  pneumonia       age  diabetes  copd  asthma  inmsupr  \
2         1        0          0  0.406015         0     0       0        0   
3         2        0          1  0.225564         0     0       0        0   
4         1        0          0  0.451128         1     0       0        0   
5         2        0          1  0.353383         1     0       0        0   
6         2        0          0  0.473684         0     0       0        0   
...     ...      ...        ...       ...       ...   ...     ...      ...   
566584    2        0          1  0.338346         0     0       0        0   
566590    2        1          1  0.511278         0     0       0        0   
566591    2        1          1  0.360902         1     0       0        0   
566593    1        0          1  0.233083         0     0       0        0   
566599    1        0          1  0.368421         0     0       0        0   

        hypertension  other_disease  cardiovascular  obesity  renal_chronic  \
2                  0              0               0        1              0   
3                  0              0               0        0              0   
4                  1              0               1        0              0   
5                  0              0               0        0              0   
6                  1              0               0        0              0   
...              ...            ...             ...      ...            ...   
566584             0              0               0        0              0   
566590             1              0               0        1              0   
566591             1              0               0        0              0   
566593             0              0               0        0              0   
566599             0              0               0        1              0   

        tobacco  
2             0  
3             0  
4             0  
5             0  
6             0  
...         ...  
566584        0  
566590        0  
566591        0  
566593        0  
566599        0  

[120182 rows x 14 columns]

In [39]:
from sklearn.model_selection import train_test_split
X=model_data.drop(['intubed'],axis=1)
y=model_data['intubed']

In [40]:
X

sex  pneumonia       age  diabetes  copd  asthma  inmsupr  \
2         1          0  0.406015         0     0       0        0   
3         2          1  0.225564         0     0       0        0   
4         1          0  0.451128         1     0       0        0   
5         2          1  0.353383         1     0       0        0   
6         2          0  0.473684         0     0       0        0   
...     ...        ...       ...       ...   ...     ...      ...   
566584    2          1  0.338346         0     0       0        0   
566590    2          1  0.511278         0     0       0        0   
566591    2          1  0.360902         1     0       0        0   
566593    1          1  0.233083         0     0       0        0   
566599    1          1  0.368421         0     0       0        0   

        hypertension  other_disease  cardiovascular  obesity  renal_chronic  \
2                  0              0               0        1              0   
3                  0              0               0        0              0   
4                  1              0               1        0              0   
5                  0              0               0        0              0   
6                  1              0               0        0              0   
...              ...            ...             ...      ...            ...   
566584             0              0               0        0              0   
566590             1              0               0        1              0   
566591             1              0               0        0              0   
566593             0              0               0        0              0   
566599             0              0               0        1              0   

        tobacco  
2             0  
3             0  
4             0  
5             0  
6             0  
...         ...  
566584        0  
566590        0  
566591        0  
566593        0  
566599        0  

[120182 rows x 13 columns]

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) 

In [42]:
from imblearn.over_sampling import SMOTE
import numpy as np
sm = SMOTE(random_state=12)
X_train_res, y_train_res = sm.fit_sample(X_train, y_train)
X_test_res, y_test_res = sm.fit_sample(X_test, y_test)
print (y_train_res.value_counts() , np.bincount(y_train_res))

1    77376
0    77376
Name: intubed, dtype: int64 [77376 77376]


In [43]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train_res,y_train_res)

y_pred=clf.predict(X_test_res)

In [45]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test_res, y_pred))

Accuracy: 0.7107809156394105


In [46]:
X_test.head()

sex  pneumonia       age  diabetes  copd  asthma  inmsupr  \
152272    2          1  0.375940         0     0       0        0   
419924    1          0  0.601504         0     0       0        0   
386262    2          0  0.360902         0     0       0        0   
416074    1          0  0.007519         0     0       0        0   
472831    1          1  0.488722         0     0       0        0   

        hypertension  other_disease  cardiovascular  obesity  renal_chronic  \
152272             0              0               0        1              0   
419924             1              1               1        0              0   
386262             1              0               0        0              0   
416074             0              0               0        0              0   
472831             0              0               1        0              0   

        tobacco  
152272        1  
419924        0  
386262        0  
416074        0  
472831        0

In [47]:
clf.predict([[1,1,0.999,1,1,1,1,1,1,1,1,1,1]])

array([0], dtype=int64)

In [48]:
clf.predict_proba([[1,1,0.999,1,1,1,1,1,1,1,1,1,1]])

array([[0.95, 0.05]])

In [49]:
clf.predict_proba([[1,1,0.50,0,1,0,0,0,1,0,1,0,0]])

array([[0.69, 0.31]])

In [50]:
clf.predict_proba([[2,0,0.002,0,0,0,0,0,0,0,0,0,0]])

array([[0.45034851, 0.54965149]])

In [51]:
clf.predict([[0,0,0.2,0,0,0,0,0,0,0,0,0,0]])

array([1], dtype=int64)

In [52]:
clf.predict(X_test.tail())

array([0, 0, 1, 0, 1], dtype=int64)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
confusion_matrix(y_test_res,y_pred)

array([[23034, 10145],
       [ 9047, 24132]], dtype=int64)

In [54]:
X_test.head()

sex  pneumonia       age  diabetes  copd  asthma  inmsupr  \
152272    2          1  0.375940         0     0       0        0   
419924    1          0  0.601504         0     0       0        0   
386262    2          0  0.360902         0     0       0        0   
416074    1          0  0.007519         0     0       0        0   
472831    1          1  0.488722         0     0       0        0   

        hypertension  other_disease  cardiovascular  obesity  renal_chronic  \
152272             0              0               0        1              0   
419924             1              1               1        0              0   
386262             1              0               0        0              0   
416074             0              0               0        0              0   
472831             0              0               1        0              0   

        tobacco  
152272        1  
419924        0  
386262        0  
416074        0  
472831        0

In [55]:
y_test.value_counts()

0    33179
1     2876
Name: intubed, dtype: int64

In [57]:
import pickle

In [63]:
with open('model_pickle.pkl','wb') as file:
    pickle.dump(clf,file)

In [64]:
with open('model_pickle.pkl','rb') as file:
    mp = pickle.load(file)

In [65]:
mp.predict_proba([[1,1,0.7,1,1,1,1,1,1,1,1,1,1]])

array([[0.95, 0.05]])